gmt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/forms.py
from django import forms

class VerificationCodeForm(forms.Form):
    verificationcode = forms.CharField(max_length=6, widget=forms.TextInput(attrs={'placeholder': '6 Digit OTP', 'class':'form-control','style':'width:323px; display:inline-block; margin:5px 0px 0px -19px;'}), label='Enter OTP')


class FileUpload(forms.Form):
    server_file_upload = forms.FileField(label='Server File', widget=forms.FileInput(attrs={'style':'width: 210px;'}))
    client_file_upload = forms.FileField(label='Client File', widget=forms.FileInput(attrs={'style':'width: 210px;'}))


class MainInput(forms.Form):
    website_domain = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'website.com', 'class':'form-control'}), label='Website Domain *', required=False)
    subdomain_of_tracking_server = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Subdomain', 'class':'form-control'}), label='Subdomain of Tracking Server *', required=False)
    gtm_web_container_id = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'GTM Web Container ID', 'class':'form-control'}), label='GTM Web Container ID *', required=False)
    ga4_property_id = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'GA4 Property ID', 'class':'form-control'}), label='GA4 Property ID *', required=False)
    ua_property_id = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'UA Property ID', 'class':'form-control'}), label='UA Property ID (Optional)', required=False)
    facebook_pixel_id = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Facebook Pixel ID', 'class':'form-control'}), label='Facebook Pixel ID *', required=False)
    facebook_auth_token = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Facebook Auth Token', 'class':'form-control'}), label='Facebook Auth Token *', required=False)
    connect_multiple_domains_to_the_same_server = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    hide_setup_from_ad_blockers = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    view_item_or_view_content = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    generate_lead = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    add_to_cart = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    begin_checkout_or_initiate_checkout = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    purchase = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    add_payment_info = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    add_to_wishlist = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    sign_up_or_complete_registration = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    search = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    contact = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    customize_product = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    donate = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    find_location = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    schedule = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    start_trial = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    submit_application = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)
    subscribe = forms.BooleanField(widget=forms.CheckboxInput(attrs={'type':'checkbox'}), required=False)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E25_GTM | {% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<style>
    .btn{
        margin-top: 5px;
    }

    #loader {
        position: absolute;
        width: 100%;
        height: 100%;
        background: #fff;
        z-index: 999999;
    }

    .loadBar {
        position: absolute;
        top: 35%;
        background: #fff;
        width: 100%;
        text-align: center;    }
    
    {% block css %}  {% endblock %}
</style>

<body class="d-flex justify-content-center" style="margin: 20px;">
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    {% block content_js %} {% endblock %}
</body>
</html>

templates/download_json_file.html
{% extends 'base.html' %}

{% block title %}
download_file
{% endblock %}

{% block content %}
{% load static %}

<div id="loader">
    <div class="loadBar">
        <img class="animation__shake" src="{% static 'spinning_load.gif' %}" alt="Loading" height="100" >
        <h5>Hold tight, we're generating files for download...</h5>
        <p>This can take a moment</p>
    </div>
</div>

<div class="form-group" style="margin: 20px;width: 414px;">
    {% for message in messages %}
    {% if 'success' in message.tags %}
    <div class="alert-dismissible fade show alert alert-success" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% if 'error' in message.tags %}
    <div class="alert-dismissible fade show alert alert-danger" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    <form action="" method="post">
        {% csrf_token %}
        <a href="/mainform" class="btn btn-outline-dark" name="start_over" id="start_over_id">Start Over</a>
        <a href="/logout" class="btn btn-secondary" name="sign_out" id="sign_out_id" style="float: right;">Sign Out</a>
        <br>

        <div style="width: 100%; padding: 10px 60px;">
            <label>Here are your files:</label>
            <br>
            <a download href="/static/server_json_files/{{server_updated_file_name}}" class="btn btn-primary" name="server_file_download" id="download_server_file"
                style="width: 100%;">Download Server File</a>
            <br>
            <a download href="/static/client_json_files/{{client_updated_file_name}}" class="btn btn-primary" name="client_file_download" id="download_client_file"
                style="width: 100%;">Download Client File</a>
        <br>
        
        </div>
        <label style="margin-left: 7px;">Your Updated GTM Container Code:</label>
        <textarea name="Updated_gtm_ontainer_code" id="Updated_gtm_ontainer_code_id" cols="42" rows="12" style="font-size: 15px;margin-left: 7px;"><!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://{{website_subdomain}}.{{website_domain}}/{{gtm_endpoint}}?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','{{web_container_id}}');</script>
<!-- End Google Tag Manager --></textarea>
    </form>

</div>

{% endblock %}

{% block content_js %}
<script src="{% static 'js/download_json_file.js' %}"></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
HOME
{% endblock %}

{% block content %}
{% load static %}

<div id="loader">
    <div class="loadBar text-center">
        <img class="animation__shake" src="{% static 'spinning_load.gif' %}" alt="Loading" height="100" >
        <p>Wait a moment</p>
    </div>
</div>

<div class="form-group" style="margin: 20px;width: 414px;">
    {% for message in messages %}
    {% if 'success' in message.tags %}
    <div class="alert-dismissible fade show alert alert-success" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% if 'error' in message.tags %}
    <div class="alert-dismissible fade show alert alert-danger" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    
    <h4>Select server JSON File or Client JSON File.</h4>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.server_file_upload.label_tag }}
        <br>
        {{ form.server_file_upload }}
        <input type="submit" class="btn btn-primary" name="Upload_server_file" value="Server .JSON" style="float: right;width: 125px;">
    </form>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.client_file_upload.label_tag }}
        <br>
        {{ form.client_file_upload }}
        <input type="submit" class="btn btn-primary" name="Upload_client_file" value="Client .JSON" style="float: right;width: 125px;">
    </form>
</div>

{% endblock %}
</html>

{% block content_js %}
<script src="{% static 'js/home.js' %}"></script>
{% endblock %}

templates/main_input_form.html
{% extends 'base.html' %}

{% block title %}
Input Form
{% endblock %}

{% block content %}
{% load static %}

<div id="loader">
    <div class="loadBar">
        <img class="animation__shake" src="{% static 'spinning_load.gif' %}" alt="Loading" height="100" >
        <h5>Hold tight, we're generating your files...</h5>
        <p>This can take a moment</p>
    </div>
</div>

<div class="form-group" id="data_show" style="margin: 20px;width: 420px;">
    {% for message in messages %}
    {% if 'success' in message.tags %}
    <div class="alert-dismissible fade show alert alert-success" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% if 'error' in message.tags %}
    <div class="alert-dismissible fade show alert alert-danger" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}

    <button class="btn btn-outline-dark" name="clear_form" id="clean_main_form">Clear Form Fields</button>
    <button class="btn btn-secondary" name="clear_form" id="sign_out_main_form" style="float: right;">Sign Out</button>
    <form action="" method="post">
        {% csrf_token %}

        {{ form.website_domain.label_tag }}
        {{ form.website_domain }}
        {{ form.subdomain_of_tracking_server.label_tag }}
        {{ form.subdomain_of_tracking_server }}
        {{ form.gtm_web_container_id.label_tag }}
        {{ form.gtm_web_container_id }}
        {{ form.ga4_property_id.label_tag }}
        {{ form.ga4_property_id }}
        {{ form.ua_property_id.label_tag }}
        {{ form.ua_property_id }}
        {{ form.facebook_pixel_id.label_tag }}
        {{ form.facebook_pixel_id }}
        {{ form.facebook_auth_token.label_tag }}
        {{ form.facebook_auth_token }}

        <!-- {% if file_type == 'server' %}

        {{ form.gtm_web_container_id.label_tag }}
        {{ form.gtm_web_container_id }}
        {{ form.ga4_property_id.label_tag }}
        {{ form.ga4_property_id }}
        {{ form.ua_property_id.label_tag }}
        {{ form.ua_property_id }}
        {{ form.facebook_pixel_id.label_tag }}
        {{ form.facebook_pixel_id }}
        {{ form.facebook_auth_token.label_tag }}
        {{ form.facebook_auth_token }}

        {% elif file_type == 'client' %}
        
        {{ form.website_domain.label_tag }}
        {{ form.website_domain }}
        {{ form.subdomain_of_tracking_server.label_tag }}
        {{ form.subdomain_of_tracking_server }}
        {{ form.gtm_web_container_id.label_tag }}
        {{ form.gtm_web_container_id }}
        {{ form.ga4_property_id.label_tag }}
        {{ form.ga4_property_id }}
        {{ form.facebook_pixel_id.label_tag }}
        {{ form.facebook_pixel_id }}

        {% endif %} -->

        {{ form.connect_multiple_domains_to_the_same_server }}
        <label for="id_connect_multiple_domains_to_the_same_server">Connect Multiple Domains to the Same Server
            (Agency)</label>
        <br>
        {{ form.hide_setup_from_ad_blockers }}
        <label for="id_hide_setup_from_ad_blockers">Hide Setup From Ad Blockers</label>
        <br>
        <br>
        <label>Events to track:</label>
        <br>
        {{ form.view_item_or_view_content }}
        <label for="id_view_item_or_view_content">view_item / ViewContent</label>
        <br>
        {{ form.generate_lead }}
        <label for="id_generate_lead">generate_lead / Lead</label>
        <br>
        {{ form.add_to_cart }}
        <label for="id_add_to_cart">add_to_cart / AddToCart</label>
        <br>
        {{ form.begin_checkout_or_initiate_checkout }}
        <label for="id_begin_checkout_or_initiate_checkout">begin_checkout / InitiateCheckout</label>
        <br>
        {{ form.purchase }}
        <label for="id_purchase">purchase / Purchase</label>
        <br>
        {{ form.add_payment_info }}
        <label for="id_add_payment_info">add_payment_info / AddPaymentInfo</label>
        <br>
        {{ form.add_to_wishlist }}
        <label for="id_add_to_wishlist">add_to_wishlist / AddToWishlist</label>
        <br>
        {{ form.sign_up_or_complete_registration }}
        <label for="id_sign_up_or_complete_registration">sign_up / CompleteRegistration</label>
        <br>
        {{ form.search }}
        <label for="id_search">search / Search</label>
        <br>
        {{ form.contact }}
        <label for="id_contact">contact / Contact</label>
        <br>
        {{ form.customize_product }}
        <label for="id_customize_product">customize_product / CustomizeProduct</label>
        <br>
        {{ form.donate }}
        <label for="id_donate">donate / Donate</label>
        <br>
        {{ form.find_location }}
        <label for="id_find_location">find_location / FindLocation</label>
        <br>
        {{ form.schedule }}
        <label for="id_schedule">schedule / Schedule</label>
        <br>
        {{ form.start_trial }}
        <label for="id_start_trial">start_trial / StartTrial</label>
        <br>
        {{ form.submit_application }}
        <label for="id_submit_application">submit_application / SubmitApplication</label>
        <br>
        {{ form.subscribe }}
        <label for="id_subscribe">subscribe / Subscribe</label>
        <br>
        <div style="padding: 0% 40%;">
            <input type="submit" class="btn btn-primary" value="Submit" style="width: 100%;">
        </div>
    </form>
</div>


{% endblock %}

{% block content_js %}
<script src="{% static 'js/main_input_form.js' %}"></script>
{% endblock %}

templates/singup.html
{% extends 'base.html' %}

{% block title %}
Sing Up
{% endblock %}

{% block content %}
{% load static %}

<div class="form-group" style="margin: 20px;width: 414px;">
    {% for message in messages %}
    {% if 'success' in message.tags %}
    <div class="alert-dismissible fade show alert alert-success" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% if 'error' in message.tags %}
    <div class="alert-dismissible fade show alert alert-danger" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}

    <form action="" method="post">
        {% csrf_token %}

        <input type="text" name="mail" placeholder="Your Email Address..." class="form-control set_mail" id="GET_OTP" aria-label="Example text with button addon" aria-describedby="GET_OTP" maxlength="255" >
        <div class="row">
            <div class="col-3">
                <input type="button" name="Send_code" class="btn btn-primary send_Mail" value="Get OTP" id="send_Email">
            </div>
            <div class="col-9">
                {{ form1.verificationcode }}
            </div>
        </div>
           
        <input type="submit" name="Login_User" class="btn btn-primary " value="Sign In" style="width: 100%;">
    </form>
</div>

{% endblock %}

{% block content_js %}
<script>
    document.getElementById("id_verificationcode").required = false;
</script>

<script src="{% static 'js/singup.js' %}"></script>
{% endblock %}

templates/user_home.html
{% extends 'base.html' %}

{% block title %}
USER_HOME
{% endblock %}

{% block content %}
{% load static %}

<div id="loader">
    <div class="loadBar text-center">
        <img class="animation__shake" src="{% static 'spinning_load.gif' %}" alt="Loading" height="100" >
        <p>Wait a moment</p>
    </div>
</div>

<div class="form-group" style="margin: 20px;width: 414px;">
    {% for message in messages %}
    {% if 'success' in message.tags %}
    <div class="alert-dismissible fade show alert alert-success" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% if 'error' in message.tags %}
    <div class="alert-dismissible fade show alert alert-danger" role="alert">
    {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    
    <h4 class="text-center">Select JSON File Type:</h4>
    <br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary " name="Upload_server_file" value="Server .JSON" style="float: right;width: 45%;">
    </form>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" name="Upload_client_file" value="Client .JSON" style="float: left;width: 45%">
    </form>
</div>

{% endblock %}
</html>

{% block content_js %}
<script src="{% static 'js/home.js' %}"></script>
{% endblock %}